config/routes.rb
Rails.application.routes.draw do
  resources :requests
  resources :references do
    resources :reference_lists
  end

  get 'welcome/index'

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks',registrations: 'users/registrations' }

  root 'welcome#index'

  concern :common_user do
    resources :requests
  end

  resources :worker_profiles, concerns: :common_user
  resources :customer_profiles, concerns: :common_user

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" style="margin-bottom: 0px">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Project Fernandez</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Nosotros <span class="sr-only">(current)</span></a></li>
        <li><a href="<%= worker_profiles_path %>">Workers</a></li>
        <li><a href="<%= customer_profiles_path %>">Customers</a></li>
        <% if current_user != nil && current_user.profile_type == 'CustomerProfile'%>
          <li><a href="<%= new_request_path %>">Requests</a></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user.nil? %>
          <li><a href="<%= new_user_session_path %>">Ingreso</a></li>
          <li><a href="<%= new_user_registration_path %>">Registro</a></li>
        <% else %>
          <li><a href="<%= destroy_user_session_path %>" data-method="delete">Salir</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>