config/routes.rb
Rails.application.routes.draw do
  resources :requests
  resources :references do
    resources :reference_lists
  end

  get 'welcome/index'

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks',registrations: 'users/registrations' }

  root 'welcome#index'

  concern :common_user do
    resources :requests
  end

  resources :worker_profiles, concerns: :common_user
  resources :customer_profiles, concerns: :common_user

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :customer_profile, inverse_of: :requests
  belongs_to :worker_profile, inverse_of: :requests
  belongs_to :state, :class_name => 'ReferenceList'
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:description, :message, :customer_profile_id, :worker_profile_id, :comment, :rating, :price, :work_hours)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :customer_profile_id %><br>
    <%= f.text_field :customer_profile_id %>
  </div>
  <div class="field">
    <%= f.label :worker_profile_id %><br>
    <%= f.text_field :worker_profile_id %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :work_hours %><br>
    <%= f.number_field :work_hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Requests</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Message</th>
      <th>Customer profile</th>
      <th>Worker profile</th>
      <th>Comment</th>
      <th>Rating</th>
      <th>Price</th>
      <th>Work hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.description %></td>
        <td><%= request.message %></td>
        <td><%= request.customer_profile %></td>
        <td><%= request.worker_profile %></td>
        <td><%= request.comment %></td>
        <td><%= request.rating %></td>
        <td><%= request.price %></td>
        <td><%= request.work_hours %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @request.description %>
</p>

<p>
  <strong>Message:</strong>
  <%= @request.message %>
</p>

<p>
  <strong>Customer profile:</strong>
  <%= @request.customer_profile %>
</p>

<p>
  <strong>Worker profile:</strong>
  <%= @request.worker_profile %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @request.comment %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @request.rating %>
</p>

<p>
  <strong>Price:</strong>
  <%= @request.price %>
</p>

<p>
  <strong>Work hours:</strong>
  <%= @request.work_hours %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>