config/routes.rb
Rails.application.routes.draw do
  resources :requests
  resources :references do
    resources :reference_lists
  end

  get 'welcome/index'

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks',registrations: 'users/registrations' }

  root 'welcome#index'

  concern :common_user do
    resources :requests
  end

  resources :worker_profiles, concerns: :common_user
  resources :customer_profiles, concerns: :common_user

end

app/models/reference_list.rb
class ReferenceList < ActiveRecord::Base
  belongs_to :reference, inverse_of: :reference_lists

  has_many   :states, :class_name => 'Request', :foreign_key => 'state_id'

end

app/controllers/reference_lists_controller.rb
class ReferenceListsController < ApplicationController
  before_action :set_reference_list, only: [:show, :edit, :update, :destroy]

  # GET /reference_lists
  # GET /reference_lists.json
  def index
    @reference_lists = ReferenceList.all
  end

  # GET /reference_lists/1
  # GET /reference_lists/1.json
  def show
  end

  # GET /reference_lists/new
  def new
    @reference_list = ReferenceList.new
  end

  # GET /reference_lists/1/edit
  def edit
  end

  # POST /reference_lists
  # POST /reference_lists.json
  def create
    @reference_list = ReferenceList.new(reference_list_params)

    respond_to do |format|
      if @reference_list.save
        format.html { redirect_to @reference_list, notice: 'Reference list was successfully created.' }
        format.json { render :show, status: :created, location: @reference_list }
      else
        format.html { render :new }
        format.json { render json: @reference_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reference_lists/1
  # PATCH/PUT /reference_lists/1.json
  def update
    respond_to do |format|
      if @reference_list.update(reference_list_params)
        format.html { redirect_to @reference_list, notice: 'Reference list was successfully updated.' }
        format.json { render :show, status: :ok, location: @reference_list }
      else
        format.html { render :edit }
        format.json { render json: @reference_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reference_lists/1
  # DELETE /reference_lists/1.json
  def destroy
    @reference_list.destroy
    respond_to do |format|
      format.html { redirect_to reference_lists_url, notice: 'Reference list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference_list
      @reference_list = ReferenceList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reference_list_params
      params.require(:reference_list).permit(:name, :description, :value, :reference_id)
    end
end

app/helpers/reference_lists_helper.rb
module ReferenceListsHelper
end

app/views/reference_lists/_form.html.erb
<%= form_for(@reference_list) do |f| %>
  <% if @reference_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reference_list.errors.count, "error") %> prohibited this reference_list from being saved:</h2>

      <ul>
      <% @reference_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :reference_id %><br>
    <%= f.text_field :reference_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reference_lists/edit.html.erb
<h1>Editing Reference List</h1>

<%= render 'form' %>

<%= link_to 'Show', @reference_list %> |
<%= link_to 'Back', reference_lists_path %>

app/views/reference_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reference Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Value</th>
      <th>Reference</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reference_lists.each do |reference_list| %>
      <tr>
        <td><%= reference_list.name %></td>
        <td><%= reference_list.description %></td>
        <td><%= reference_list.value %></td>
        <td><%= reference_list.reference %></td>
        <td><%= link_to 'Show', reference_list %></td>
        <td><%= link_to 'Edit', edit_reference_list_path(reference_list) %></td>
        <td><%= link_to 'Destroy', reference_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reference list', new_reference_list_path %>

app/views/reference_lists/new.html.erb
<h1>New Reference List</h1>

<%= render 'form' %>

<%= link_to 'Back', reference_lists_path %>

app/views/reference_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reference_list.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @reference_list.description %>
</p>

<p>
  <strong>Value:</strong>
  <%= @reference_list.value %>
</p>

<p>
  <strong>Reference:</strong>
  <%= @reference_list.reference %>
</p>

<%= link_to 'Edit', edit_reference_list_path(@reference_list) %> |
<%= link_to 'Back', reference_lists_path %>